blank_issues_enabled: false
contact_links:
  - name: Open a Discussion
    url: https://github.com/dotnet/csharplang/discussions/new
    about: Please open new proposals as discussions if they are not fully specified.
